// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Schedule struct {
	ID            uuid.UUID          `json:"id"`
	Userid        uuid.UUID          `json:"userid"`
	LeavingDate   pgtype.Timestamptz `json:"leaving_date"`
	ReturningDate pgtype.Timestamptz `json:"returning_date"`
	Overseas      bool               `json:"overseas"`
	LastChangedBy string             `json:"last_changed_by"`
	LastChanged   pgtype.Timestamptz `json:"last_changed"`
}

type User struct {
	ID          uuid.UUID   `json:"id"`
	Upn         string      `json:"upn"`
	DisplayName string      `json:"display_name"`
	Staff       pgtype.Bool `json:"staff"`
}
