// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchedule, id)
	return err
}

const flipSchedule = `-- name: FlipSchedule :exec
UPDATE schedules
SET overseas = true
WHERE id = $1
`

func (q *Queries) FlipSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, flipSchedule, id)
	return err
}

const getSchdeule = `-- name: GetSchdeule :one
SELECT id, userid, leaving_date, returning_date, overseas, last_changed_by, last_changed from schedules WHERE ID = $1
`

func (q *Queries) GetSchdeule(ctx context.Context, id uuid.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchdeule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.LeavingDate,
		&i.ReturningDate,
		&i.Overseas,
		&i.LastChangedBy,
		&i.LastChanged,
	)
	return i, err
}

const insertSchedule = `-- name: InsertSchedule :one
INSERT INTO schedules (userID, leaving_date, returning_date, last_changed_by) 
VALUES ($1, $2, $3, $4) 
RETURNING id, userid, leaving_date, returning_date, overseas, last_changed_by, last_changed
`

type InsertScheduleParams struct {
	Userid        uuid.UUID          `json:"userid"`
	LeavingDate   pgtype.Timestamptz `json:"leaving_date"`
	ReturningDate pgtype.Timestamptz `json:"returning_date"`
	LastChangedBy string             `json:"last_changed_by"`
}

func (q *Queries) InsertSchedule(ctx context.Context, arg InsertScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, insertSchedule,
		arg.Userid,
		arg.LeavingDate,
		arg.ReturningDate,
		arg.LastChangedBy,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.LeavingDate,
		&i.ReturningDate,
		&i.Overseas,
		&i.LastChangedBy,
		&i.LastChanged,
	)
	return i, err
}

const listScheduleSummaries = `-- name: ListScheduleSummaries :many
SELECT 
	schedules.id, 
	schedules.userID, 
	users.display_name, 
	users.upn, 
	schedules.leaving_date, 
	schedules.returning_date, 
	schedules.overseas, 
	schedules.last_changed_by, 
	schedules.last_changed 
FROM schedules 
INNER JOIN users ON schedules.userID = users.id
`

type ListScheduleSummariesRow struct {
	ID            uuid.UUID          `json:"id"`
	Userid        uuid.UUID          `json:"userid"`
	DisplayName   string             `json:"display_name"`
	Upn           string             `json:"upn"`
	LeavingDate   pgtype.Timestamptz `json:"leaving_date"`
	ReturningDate pgtype.Timestamptz `json:"returning_date"`
	Overseas      bool               `json:"overseas"`
	LastChangedBy string             `json:"last_changed_by"`
	LastChanged   pgtype.Timestamptz `json:"last_changed"`
}

func (q *Queries) ListScheduleSummaries(ctx context.Context) ([]ListScheduleSummariesRow, error) {
	rows, err := q.db.Query(ctx, listScheduleSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleSummariesRow
	for rows.Next() {
		var i ListScheduleSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.DisplayName,
			&i.Upn,
			&i.LeavingDate,
			&i.ReturningDate,
			&i.Overseas,
			&i.LastChangedBy,
			&i.LastChanged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE schedules
SET 
	leaving_date = $2, 
	returning_date = $3, 
	overseas = $4, 
	last_changed_by = $5, 
	last_changed = NOW()
WHERE id = $1
`

type UpdateScheduleParams struct {
	ID            uuid.UUID          `json:"id"`
	LeavingDate   pgtype.Timestamptz `json:"leaving_date"`
	ReturningDate pgtype.Timestamptz `json:"returning_date"`
	Overseas      bool               `json:"overseas"`
	LastChangedBy string             `json:"last_changed_by"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.Exec(ctx, updateSchedule,
		arg.ID,
		arg.LeavingDate,
		arg.ReturningDate,
		arg.Overseas,
		arg.LastChangedBy,
	)
	return err
}
