// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urgent_jobs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUrgentSchedule = `-- name: DeleteUrgentSchedule :exec
DELETE FROM urgent_schedules WHERE id = $1
`

func (q *Queries) DeleteUrgentSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUrgentSchedule, id)
	return err
}

const insertUrgentSchedule = `-- name: InsertUrgentSchedule :one
INSERT INTO urgent_schedules (userID) 
VALUES ($1) 
RETURNING id, userid
`

func (q *Queries) InsertUrgentSchedule(ctx context.Context, userid uuid.UUID) (UrgentSchedule, error) {
	row := q.db.QueryRow(ctx, insertUrgentSchedule, userid)
	var i UrgentSchedule
	err := row.Scan(&i.ID, &i.Userid)
	return i, err
}

const listUrgentSchedules = `-- name: ListUrgentSchedules :many
SELECT urgent_schedules.id, userid, users.id, upn, display_name, staff FROM urgent_schedules
INNER JOIN users ON urgent_schedules.userID = users.id
`

type ListUrgentSchedulesRow struct {
	ID          uuid.UUID   `json:"id"`
	Userid      uuid.UUID   `json:"userid"`
	ID_2        uuid.UUID   `json:"id_2"`
	Upn         string      `json:"upn"`
	DisplayName string      `json:"display_name"`
	Staff       pgtype.Bool `json:"staff"`
}

func (q *Queries) ListUrgentSchedules(ctx context.Context) ([]ListUrgentSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listUrgentSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUrgentSchedulesRow
	for rows.Next() {
		var i ListUrgentSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.ID_2,
			&i.Upn,
			&i.DisplayName,
			&i.Staff,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
