// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_assets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getUserAsset = `-- name: GetUserAsset :one
SELECT userid, content_type, data, created_at, updated_at
FROM user_assets
WHERE userID = $1
`

func (q *Queries) GetUserAsset(ctx context.Context, userid uuid.UUID) (UserAsset, error) {
	row := q.db.QueryRow(ctx, getUserAsset, userid)
	var i UserAsset
	err := row.Scan(
		&i.Userid,
		&i.ContentType,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserAsset = `-- name: UpsertUserAsset :one
INSERT INTO user_assets (userID, content_type, data)
VALUES ($1, $2, $3)
ON CONFLICT (userID)
DO UPDATE SET
	content_type = EXCLUDED.content_type,
	data = EXCLUDED.data,
	updated_at = NOW()
RETURNING userid, content_type, data, created_at, updated_at
`

type UpsertUserAssetParams struct {
	Userid      uuid.UUID `json:"userid"`
	ContentType string    `json:"content_type"`
	Data        []byte    `json:"data"`
}

func (q *Queries) UpsertUserAsset(ctx context.Context, arg UpsertUserAssetParams) (UserAsset, error) {
	row := q.db.QueryRow(ctx, upsertUserAsset, arg.Userid, arg.ContentType, arg.Data)
	var i UserAsset
	err := row.Scan(
		&i.Userid,
		&i.ContentType,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
