// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE
FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserByUPN = `-- name: DeleteUserByUPN :exec
DELETE
FROM users
WHERE upn = $1
`

func (q *Queries) DeleteUserByUPN(ctx context.Context, upn string) error {
	_, err := q.db.Exec(ctx, deleteUserByUPN, upn)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, upn, display_name, staff
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Upn,
		&i.DisplayName,
		&i.Staff,
	)
	return i, err
}

const getUserByUPN = `-- name: GetUserByUPN :one
SELECT id, upn, display_name, staff
FROM users
WHERE upn = $1
`

func (q *Queries) GetUserByUPN(ctx context.Context, upn string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUPN, upn)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Upn,
		&i.DisplayName,
		&i.Staff,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, upn, display_name, staff
FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Upn,
			&i.DisplayName,
			&i.Staff,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, upn, display_name, staff)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id)
DO UPDATE SET
	upn = EXCLUDED.upn,
	display_name = EXCLUDED.display_name
RETURNING id, upn, display_name, staff
`

type UpsertUserParams struct {
	ID          uuid.UUID   `json:"id"`
	Upn         string      `json:"upn"`
	DisplayName string      `json:"display_name"`
	Staff       pgtype.Bool `json:"staff"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Upn,
		arg.DisplayName,
		arg.Staff,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Upn,
		&i.DisplayName,
		&i.Staff,
	)
	return i, err
}
